### PR TITLE
Simpler email links

### PR DESCRIPTION
**Pull request by jschr**
Simplified the frontend endpoints that handle confirm email and password reset. Passing in user id isn't necessary.

### CODE REVIEW

**Comment by KristerV** [comment]
Okay, makes sense. It'd be nice if the route stayed under `/users` though.

**Comment by jschr** [comment]
Just to clarify, these are the frontend urls. There's no `/users` page in the frontend at the moment so I'm not sure how that works with nextjs.

**Comment by KristerV** [comment]
oh my bad. that's totally fine then. It's looking like my comments are just slowing you down and not actually making anything better :D

**Comment by jschr** [comment]
Not at all! I've just been busy the last couple days. Will have some time tonight to work on this.

**Pull request merged**
